<?php require_once('header.php'); ?>
<h3><strong>The STI Story</strong></h3>
<hr>
    <p id="pf">STI in Naga has been providing quality education to Bicolano youth since the early 2000. By that period, the growth of the Institution had been slow and flat since then allowing locally-based competitors to take strong hold of the market.<p id="pf"> In 2007, STI Education Services Group took full control of the operations of the school. Since then, STI introduced innovations in Academics, Marketing, Human Resource and Organizational Development and Finance that eventually lead to the continuous growth of the organization.<p id="pf">
The visionary in STI President Atty. Monico V. Jacob saw the growing demand for quality education in the Region, particularly in Naga City which is considered as the heart of Bicolandia.<p id="pf">  While no doubt opportunity abounds in the Region, the current business position of being an Education Center offering short-term to a maximum of 2-year vocational programs inherently imposed limitations to the growth of the Institution. thus, in the early part of 2009, STI took its first giant step and embarked on a different, demanding the most-challenging journey to the future of education. The primary goal then is to reposition the STI brand by upgrading into a full-pledge College Intuition.
        Repositioning requires added resources to succeed. Thus, in 2010, STI dared to take the challenge a step higher with the eventual construction of a Multi-Million Peso Project at the Central Business District II property STI bought a year before.<p id="pf">  A new STI Academic Center will be standing in an imposing manner right at Heart of Bicolandia. The Academic Center was built on a 5,000 sqm property which can accommodate over 5,000 students. Equipped with the latest facilities in Information and Communications Technology, Engineering, Hospitality & Restaurant Management and Tourism, the Academic Center was uniquely designed according to industry standards to better simulate real life corporate practices in a classroom to further prepare its students.
        SY 2010-2011 is the most challenging school year thus far, this marks several important milestones in the history of STI in Naga as follows:<p id="pf">  (1) By this year, STI had finally upgraded into a College status offering four (4) degree programs, (2) groundbreaking and construction of the new STI Academic Center in Naga started almost simultaneously, (3) provision of an “annex” campus during the first semester at AMS building along Peñafrancia Avenue due to over capacity concerns at the old Phoenician building campus. BUT, that was before we hit a slump 2 years after.
        Inaugurated January 31, 2011, the STI Academic Center is a testament of STI’s continuing commitment to uphold academic excellence for the Bicolano youth.<p id="pf">  And true enough, right after its formal opening, STI College Naga recorded another phenomenal student’s enrollment for each of the programs offered by the Institution. With the record-breaking enrollment numbers, STI College Naga has further improved its average NS enrollment growth by 3 percentage points (64% coming from 61% average NS enrollment increase since 2007) leading to the highest average annual enrollment since STI ESG took full control of STI Naga
    </p>
    <h3><strong>Enrollment to Employment (E2E) System</strong></h3>
    <hr>
    <p id="pf"> Establishing one’s career in today’s competitive industries has become a challenging pursuit to most job seekers. Employers too are increasingly having difficulty finding the right person for the job. Too often, there remains a huge gap between the skills required by the industry and what a graduate has to offer.
    STI steps up to bridge this gap by introducing the Enrollment to Employment or E2E System. The E2E System is a complete approach to human resource development, which aims to develop ICT-enabled professionals through innovative learning and career planning methodologies. Through the E2E System, STI students get applicable education, job market skills, job preparedness, and job placement assistance.
    The first step is the Learning Systems Development which ensures that the curriculum content is up-to-date and job market-oriented. A group of exemplary professionals in various fields prepares the curriculum/curricula being taught in all STI campuses.
    To make sure that the courses being offered are carried out well, STI implements the Academic Delivery System. This guarantees that highly qualified faculty and the state-of-the-art facilities of campuses are at par with the standardized courseware and curriculum, thus providing world class learning across all STI campuses.
    The third step, Student Certification, assures that students are prepared for employment through rigid assessment, evaluation, and certificate programs. Before the students leave the security of their four-walled classrooms, they are given the opportunity to undergo on-the-job training with some of STI’s reputable partner companies.
    STI’s responsibility to its graduates goes beyond quality education. The final step, Job Placement Assistance, warrants every graduate employment support with the help of Interactive - Career Assistance Recruitment System (I-CARES) and international placement agencies like GROW, INC.
    With these unique processes making up the E2E System, STI has become a pioneer all over again. It has introduced a holistic approach to education and bravely took on the challenge to ensure a bright future for its graduates through job placement assistance and a stronger alumni support system. The E2E System has redefined the landscape of the education sector.
    </p>
<?php require_once('footer.php');?>